Update phpcs.yml

diff --git a/.github/workflows/phpcs.yml b/.github/workflows/phpcs.yml
--- a/.github/workflows/phpcs.yml
+++ b/.github/workflows/phpcs.yml
@@ -20,7 +20,7 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  RUN_ON_CHANGESET: ${{ github.event_name == 'pull_request' }}
+  RUN_ON_CHANGESET: ${{ github.event_name == 'pull_request' }}  
   
 jobs:
   tests:
@@ -57,22 +57,26 @@ jobs:
           COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{secrets.CSPF_REPO_READ_PAT}}"}}'
         run: composer update
 
-      - name: Check CS on PR
-        if: ${{ env.RUN_ON_CHANGESET == 'true' }}
+      - name: Determine Check CS Scope
         env:
           PR_NUMBER: ${{ github.event.number }}
           GH_TOKEN: ${{ secrets.CSPF_REPO_READ_PAT }}        
-        shell: bash {0}
+        shell: bash {0} # Needed b/c by default of the fast-failure behavior of the github shell.
         run: |
           CHANGESET=`gh pr diff ${PR_NUMBER} --name-only`
-          if [[ $? -eq 0 ]]; then
-            # Run only on changed existing files (see the `find` part below ) if any (xarg -r)
-            echo $CHANGESET | xargs find 2> /dev/null | xargs -r composer run cs-check -- --runtime-set ignore_warnings_on_exit true
-          else
+          if [[ $? -ne 0 ]]; then
             # An error occurred, e.g. the number of changed files exceeded the limit (300).            
             # Set the env variable to run the CS check on the whole codebase.
-            echo RUN_ON_CHANGESET='false' >> $GITHUB_ENV
+            echo RUN_ON_CHANGESET='false' >> $GITHUB_ENV          
+          else
+            # Store the changeset in an env variable,
+            echo CHANGESET=${CHANGESET} >> $GITHUB_ENV          
           fi
+          
+      - name: Check CS on PR
+        if: ${{ env.RUN_ON_CHANGESET == 'true' }}            
+        run: |
+          echo env.CHANGESET | xargs find 2> /dev/null | xargs -r composer run cs-check -- --runtime-set ignore_warnings_on_exit true          
 
       - name: Check CS
         if: ${{ env.RUN_ON_CHANGESET == 'false' }}
